version: "3.9"

services:

  mysql_db:
    container_name: "mysql_db"
    image: mysql:5.7
    networks:
      - reseau
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "dbcounter"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./database/:/var/lib/mysql
    
  web:
    depends_on:
      - mysql_db
    build:
      context: .
      dockerfile : Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - reseau
    depends_on:
      - mysql_db

networks:
  reseau: